### PR TITLE
Handle failure to ACK addr on chip wakeup

### PR DESCRIPTION
**Pull request by Gadgetoid**
The APDS9500 requires a non-standard i2c "wakeup" command from a cold start.

This entails writing its i2c address (0x73) to the bus. However it will not ACK this byte, resulting in an IO exception (tested on a Raspberry Pi 4).

This patch attempts to handle the IO exception, wait for wakeup to complete, and re-initialise the library.

A noticeable side-effect of this crude approach (chosen to avoid loops or any added complexity to the underlying libraries) is a double exception stack when the board truly isn't present.

While I hesitate to add a dependency (even `time`) the addition of `time.sleep(0.1)` is required to avoid the second attempt at initialising `I2CDevice` falling within the APDS9500 wakeup time.

### CODE REVIEW

**Comment by siddacious** [comment]
I checked this on my mac last night and didn't get the NACK error until it tried to set the bank, so I'm going to re-test on a pi before deciding what the best course of action is

**Comment by siddacious** [comment]
edit: moved into change request

**Review by siddacious — CHANGES_REQUESTED** [review]
@Gadgetoid I pushed some edits to our fork's peer to your feature branch :
https://github.com/adafruit/Adafruit_CircuitPython_APDS9500/commit/6463baf9584a62cd274af4315964170e34ad565c

it still has the double exception issue you mentioned but it addresses similar NACK-related issues on both RPi and my mac with MCP2221. It might want a bit of cleanup to reduce duplication, but tbh that's the least of this lib's issues 😅 

Please take a look and test yourself as your availability allows. If you're cool with the changes go ahead and pull them into your fork. I would have pushed there directly but I wanted to give you a chance to weigh in.

**Comment by Gadgetoid** [comment]
Changes look reasonable. Will test as soon as I can! Thank you.

It's a shame there isn't a nicer way to handle this non-standard wakeup. It's the first device I've seen that NACKs the first instance of its address on wakeup. I can see the logic behind it, but sheesh do some device manufacturers like to make life hard for us 😆 

I'm hoping to try my hand at bringing some other features online, too.

**Comment by kattni** [comment]
@Gadgetoid Have you had a chance to test the suggested changes from siddacious?

**Comment by Gadgetoid** [comment]
Thanks for the heads up @kattni - I'd moved on and forgotten about this! Eek.

@siddacious I've tested this change locally on my Pi with our APDS9500 breakout and it still functions as expected.

**Pull request merged**
